### ISSUE TITLE
keycloak-gatekeeper server will never discovered

### ISSUE THREAD

**Issue by ghost** [ibuetler/docker-keycloak-traefik-workshop#6]
Hallo,

everything I tried failed with:

`keycloak-gatekeeper_1  | {"level":"warn","ts":1561214104.8448308,"msg":"failed to get provider configuration from discovery","error":"Get https://test.auth.de/auth/realms/master/.well-known/openid-configuration: dial tcp: lookup test.auth.de on 127.0.0.11:53: no such host"}`

all hosts at 127.0.0.1

**Comment by ibuetler** [comment]
If you follow the tutorial; test.auth.de is not on 127.0.0.1 from the gatekeeper docker point of view. That's why gatekeeper cannot reach the keycloak server. If you use my docker-compose.yml with the service names, you are good. Otherwise you must set the ip of keycloak in the /etc/hosts of gatekeeper. Otherwise it won't work
